# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :yams do |yams_config|
    yams_config.vm.box = "yams"
    yams_config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    yams_config.vm.provision :shell, :path => "provision.sh"
    yams_config.vm.network :private_network, ip: "192.168.33.10"

    yams_src = ENV['YAMS_SRC']
    if yams_src
      yams_config.vm.synced_folder yams_src, '/usr/local/src/yams'
    end
  end
end
